name: repro-sample
run-name: Reproduction sample
on: 
  push:
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  initial: # this job always succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Dummy
        run: |
          echo "Hello world!"

  build:
    needs: initial # makes sure the jobs run sequential
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:

    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: download-dll
      run: |
        curl -o sample.dll https://github.com/carterjones/hello-world-dll/releases/download/v1.0.0/hello-world-x64.dll

    - name: upload-unsigned-artifact
      id: upload-unsigned-artifact
      uses: actions/upload-artifact@v4
      with:
        name: "sample" 
        if-no-files-found: error
        path: |
          ./sample.dll

    - name: sign
      uses: signpath/github-action-submit-signing-request@v1
      with:
        connector-url: 'https://githubactions.connectors.fqa.test.signpath.io:15021/'
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: '${{ vars.SIGNPATH_ORGANIZATION_ID }}'
        project-slug: 'EXE'
        signing-policy-slug:  'test-signing'
        github-artifact-id:  "${{steps.upload-unsigned-artifact.outputs.artifact-id}}"
        wait-for-completion: false
    
    - name: fail # should only fail here
      run: exit 1
